"""✅ FIX #5: CSV merger for Download tools integration."""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path
from typing import Any
from asagus.services.formatting import DataFormatter
from asagus.layers.noise_reduction import format_csv_cell


class DownloadToolsCSVMerger:
    """Merges CSV outputs from all Download tools into unified export."""

    def __init__(self, job_id: str, runs_root: Path | None = None) -> None:
        self.job_id = self._safe_job_id(job_id)
        if runs_root is None:
            download_dir = Path(__file__).resolve().parents[4] / "Download"
            runs_root = download_dir / ".asagus-runs"
        self.runs_root = runs_root
        self.job_dir = runs_root / self.job_id

    @staticmethod
    def _safe_job_id(job_id: str) -> str:
        safe = re.sub(r"[^a-zA-Z0-9_.-]+", "-", str(job_id)).strip("-")
        return safe.replace("..", "") or "unknown"

    def find_tool_csvs(self) -> dict[str, Path]:
        """Find all CSV files generated by Download tools for this job."""
        tool_csvs: dict[str, Path] = {}
        if not self.job_dir.exists():
            return tool_csvs
        
        for csv_file in self.job_dir.glob("*.csv"):
            tool_id = csv_file.stem
            tool_csvs[tool_id] = csv_file
        
        return tool_csvs

    def find_tool_jsons(self) -> dict[str, Path]:
        """Find all JSON metadata files from Download tools."""
        tool_jsons: dict[str, Path] = {}
        if not self.job_dir.exists():
            return tool_jsons
        
        for json_file in self.job_dir.glob("*.json"):
            if json_file.stem != "pipeline":  # Skip pipeline manifest
                tool_id = json_file.stem
                tool_jsons[tool_id] = json_file
        
        return tool_jsons

    def read_csv_records(self, csv_path: Path) -> list[dict[str, Any]]:
        """Read records from a CSV file."""
        records: list[dict[str, Any]] = []
        try:
            with csv_path.open("r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    records.append(dict(row))
        except Exception:
            pass
        return records

    def normalize_record(self, record: dict[str, Any], tool_id: str) -> dict[str, Any]:
        """Normalize field names across different tools to match ASAGUS schema."""
        normalized: dict[str, Any] = {
            "source": tool_id,
        }
        
        # Common field mappings (mapping to internal ASAGUS field names)
        field_mapping = {
            "business_name": "name", "title": "name", "company_name": "name", "business": "name",
            "category": "category", "business_type": "category", "industry": "category", "type": "category",
            "phone_number": "phone", "telephone": "phone", "tel": "phone", "mobile": "phone",
            "whatsapp_number": "whatsapp", "wa": "whatsapp",
            "email_address": "email", "contact_email": "email", "mail": "email",
            "address": "address", "location": "address", "street": "address", "full_address": "address",
            "city": "city", "town": "city",
            "country": "country_code",
            "website": "website_url", "url": "website_url", "web": "website_url", "homepage": "website_url",
            "facebook": "facebook_url", "fb": "facebook_url",
            "instagram": "instagram_url", "insta": "instagram_url", "ig": "instagram_url",
            "twitter": "twitter_url", "x": "twitter_url",
            "linkedin": "linkedin_url",
            "rating": "rating", "stars": "rating",
            "reviews": "review_count", "review_count": "review_count",
        }
        
        # Apply mapping
        for original_key, value in record.items():
            original_lower = original_key.lower().replace("-", "_").replace(" ", "_")
            mapped_key = field_mapping.get(original_lower, original_lower)
            if value is None or value == "": continue
            if mapped_key not in normalized or not normalized[mapped_key]:
                normalized[mapped_key] = value
        
        return normalized

    def deduplicate_records(self, records: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Remove duplicate records based on phone, email, website."""
        seen_keys: set[str] = set()
        unique_records: list[dict[str, Any]] = []
        for record in records:
            dedup_key_parts: list[str] = []
            phone = record.get("phone", "")
            if phone:
                digits = "".join(c for c in str(phone) if c.isdigit())
                if digits: dedup_key_parts.append(f"phone:{digits}")
            email = record.get("email", "")
            if email: dedup_key_parts.append(f"email:{str(email).lower()}")
            website = record.get("website_url", "")
            if website:
                domain = DataFormatter.format_url(website)
                if domain: dedup_key_parts.append(f"website:{domain}")
            
            if not dedup_key_parts:
                unique_records.append(record)
                continue
            
            duplicate = any(kp in seen_keys for kp in dedup_key_parts)
            if not duplicate:
                for kp in dedup_key_parts: seen_keys.add(kp)
                unique_records.append(record)
        
        return unique_records

    def merge_all_csvs(
        self,
        output_path: Path | None = None,
        primary_records: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Merge ASAGUS primary records plus CSV files from Download tools and apply professional formatting."""
        if output_path is None:
            output_path = self.job_dir / f"merged_all_tools_{self.job_id}.csv"
        
        tool_csvs = self.find_tool_csvs()
        all_records: list[dict[str, Any]] = []
        tools_processed: list[str] = []

        if primary_records:
            all_records.extend([self.normalize_record(rec, "asagus-primary") for rec in primary_records])
            tools_processed.append("asagus-primary")
        
        for tool_id, csv_path in tool_csvs.items():
            records = self.read_csv_records(csv_path)
            if records:
                all_records.extend([self.normalize_record(rec, tool_id) for rec in records])
                tools_processed.append(tool_id)
        
        if not all_records:
            return {"status": "no_records_found", "records_merged": 0}
        
        unique_records = self.deduplicate_records(all_records)
        
        # Professional Header Order
        column_order = [
            "Business Name", "Category", "City", "Country", "Phone Number", "WhatsApp",
            "Email", "Email Verified", "Phone Valid", "WhatsApp Valid",
            "Website", "Website Active", "Facebook", "Instagram", "Twitter", "LinkedIn",
            "Rating", "Reviews", "Completeness Score", "Confidence Score",
            "Address", "Area", "Issues", "Needs Review", "Source", "Source URL", "ID"
        ]
        
        # Write merged CSV with professional formatting
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8-sig", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=column_order, extrasaction="ignore")
            writer.writeheader()
            
            for row in unique_records:
                # Map and Format
                formatted_row = {
                    "Business Name": row.get("name", "-"),
                    "Category": row.get("category", "-"),
                    "City": row.get("city", "-"),
                    "Country": DataFormatter.format_country(row.get("country_code", "-")),
                    "Phone Number": DataFormatter.format_phone(row.get("phone", "-"), row.get("country_code", "")),
                    "WhatsApp": DataFormatter.format_phone(row.get("whatsapp", "-"), row.get("country_code", "")),
                    "Email": row.get("email", "-"),
                    "Email Verified": DataFormatter.format_boolean(row.get("email_verified", "-")),
                    "Phone Valid": DataFormatter.format_boolean(row.get("phone_valid", "-")),
                    "WhatsApp Valid": DataFormatter.format_boolean(row.get("whatsapp_valid", "-")),
                    "Website": DataFormatter.format_url(row.get("website_url", "-")),
                    "Website Active": DataFormatter.format_boolean(row.get("website_alive", "-")),
                    "Facebook": DataFormatter.format_url(row.get("facebook_url", "-")),
                    "Instagram": DataFormatter.format_url(row.get("instagram_url", "-")),
                    "Twitter": DataFormatter.format_url(row.get("twitter_url", "-")),
                    "LinkedIn": DataFormatter.format_url(row.get("linkedin_url", "-")),
                    "Rating": row.get("rating", "-"),
                    "Reviews": row.get("review_count", "-"),
                    "Completeness Score": DataFormatter.format_score(row.get("record_completeness", 0)),
                    "Confidence Score": DataFormatter.format_score(row.get("confidence", 0)),
                    "Address": row.get("address", "-"),
                    "Area": row.get("normalized_area", "-"),
                    "Issues": ", ".join(row.get("raw_fields", {}).get("cleaning_issues", [])),
                    "Needs Review": DataFormatter.format_boolean(row.get("manual_review_required", "no")),
                    "Source": row.get("source", "-"),
                    "Source URL": row.get("source_url", "-"),
                    "ID": row.get("id", "-"),
                }
                
                # Quality Flags
                if formatted_row["Needs Review"] == "✅": formatted_row["Business Name"] += " ⚠️ REVIEW"
                if formatted_row["Completeness Score"] != "-" and float(formatted_row["Completeness Score"].strip("%")) < 70:
                    formatted_row["Business Name"] += " 📋 INCOMPLETE"
                if formatted_row["Email Verified"] == "❌": formatted_row["Email"] += " (unverified)"
                
                writer.writerow({k: format_csv_cell(v) for k, v in formatted_row.items()})
        
        return {
            "status": "success",
            "records_merged": len(unique_records),
            "output_csv": str(output_path),
        }
