"""✅ FIX #5: CSV merger for Download tools integration."""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path
from typing import Any


class DownloadToolsCSVMerger:
    """Merges CSV outputs from all Download tools into unified export."""

    def __init__(self, job_id: str, runs_root: Path | None = None) -> None:
        self.job_id = self._safe_job_id(job_id)
        if runs_root is None:
            download_dir = Path(__file__).resolve().parents[4] / "Download"
            runs_root = download_dir / ".asagus-runs"
        self.runs_root = runs_root
        self.job_dir = runs_root / self.job_id

    @staticmethod
    def _safe_job_id(job_id: str) -> str:
        safe = re.sub(r"[^a-zA-Z0-9_.-]+", "-", str(job_id)).strip("-")
        return safe.replace("..", "") or "unknown"

    def find_tool_csvs(self) -> dict[str, Path]:
        """Find all CSV files generated by Download tools for this job."""
        tool_csvs: dict[str, Path] = {}
        if not self.job_dir.exists():
            return tool_csvs
        
        for csv_file in self.job_dir.glob("*.csv"):
            tool_id = csv_file.stem
            tool_csvs[tool_id] = csv_file
        
        return tool_csvs

    def find_tool_jsons(self) -> dict[str, Path]:
        """Find all JSON metadata files from Download tools."""
        tool_jsons: dict[str, Path] = {}
        if not self.job_dir.exists():
            return tool_jsons
        
        for json_file in self.job_dir.glob("*.json"):
            if json_file.stem != "pipeline":  # Skip pipeline manifest
                tool_id = json_file.stem
                tool_jsons[tool_id] = json_file
        
        return tool_jsons

    def read_csv_records(self, csv_path: Path) -> list[dict[str, Any]]:
        """Read records from a CSV file."""
        records: list[dict[str, Any]] = []
        try:
            with csv_path.open("r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    records.append(dict(row))
        except Exception:
            pass
        return records

    def normalize_record(self, record: dict[str, Any], tool_id: str) -> dict[str, Any]:
        """Normalize field names across different tools to match ASAGUS schema."""
        normalized: dict[str, Any] = {
            "source_tool": tool_id,
        }
        
        # Common field mappings
        field_mapping = {
            # Name variations
            "business_name": "name",
            "title": "name",
            "company_name": "name",
            "business": "name",
            
            # Category variations
            "category": "category",
            "business_type": "category",
            "industry": "category",
            "type": "category",
            
            # Contact variations
            "phone_number": "phone",
            "telephone": "phone",
            "tel": "phone",
            "mobile": "phone",
            
            "whatsapp_number": "whatsapp",
            "wa": "whatsapp",
            
            "email_address": "email",
            "contact_email": "email",
            "mail": "email",
            
            # Location variations
            "address": "address",
            "location": "address",
            "street": "address",
            "full_address": "address",
            
            "city": "city",
            "town": "city",
            
            "country": "country_code",
            
            "latitude": "lat",
            "longitude": "lng",
            "lon": "lng",
            
            # Website variations
            "website": "website_url",
            "url": "website_url",
            "web": "website_url",
            "homepage": "website_url",
            
            # Social variations
            "facebook": "facebook_url",
            "fb": "facebook_url",
            "instagram": "instagram_url",
            "insta": "instagram_url",
            "ig": "instagram_url",
            "twitter": "twitter_url",
            "x": "twitter_url",
            "linkedin": "linkedin_url",
            
            # Ratings
            "rating": "rating",
            "stars": "rating",
            "reviews": "review_count",
            "review_count": "review_count",
            "reviews_count": "review_count",
        }
        
        # Apply mapping
        for original_key, value in record.items():
            original_lower = original_key.lower().replace("-", "_").replace(" ", "_")
            mapped_key = field_mapping.get(original_lower, original_lower)
            
            # Skip empty values
            if value is None or value == "":
                continue
            
            # Keep first non-empty value for each field
            if mapped_key not in normalized or not normalized[mapped_key]:
                normalized[mapped_key] = value
        
        return normalized

    def deduplicate_records(self, records: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Remove duplicate records based on phone, email, website."""
        seen_keys: set[str] = set()
        unique_records: list[dict[str, Any]] = []
        
        for record in records:
            # Create dedup key from identifying fields
            dedup_key_parts: list[str] = []
            
            # Phone-based dedup
            phone = record.get("phone", "")
            if phone:
                digits = "".join(c for c in str(phone) if c.isdigit())
                if digits:
                    dedup_key_parts.append(f"phone:{digits}")
            
            # Email-based dedup
            email = record.get("email", "")
            if email:
                dedup_key_parts.append(f"email:{str(email).lower()}")
            
            # Website-based dedup
            website = record.get("website_url", "")
            if website:
                domain = self._extract_domain(str(website))
                if domain:
                    dedup_key_parts.append(f"website:{domain}")
            
            # WhatsApp-based dedup
            whatsapp = record.get("whatsapp", "")
            if whatsapp:
                digits = "".join(c for c in str(whatsapp) if c.isdigit())
                if digits:
                    dedup_key_parts.append(f"wa:{digits}")
            
            # If no identifying fields, keep the record
            if not dedup_key_parts:
                unique_records.append(record)
                continue
            
            # Check if any key matches existing
            duplicate = False
            for key_part in dedup_key_parts:
                if key_part in seen_keys:
                    duplicate = True
                    break
            
            if not duplicate:
                for key_part in dedup_key_parts:
                    seen_keys.add(key_part)
                unique_records.append(record)
        
        return unique_records

    def merge_all_csvs(
        self,
        output_path: Path | None = None,
        primary_records: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Merge ASAGUS primary records plus CSV files from Download tools."""
        if output_path is None:
            output_path = self.job_dir / f"merged_all_tools_{self.job_id}.csv"
        
        tool_csvs = self.find_tool_csvs()
        primary_records = primary_records or []
        if not tool_csvs and not primary_records:
            return {
                "status": "no_csvs_found",
                "job_id": self.job_id,
                "job_dir": str(self.job_dir),
                "records_merged": 0,
            }
        
        # Collect all records
        all_records: list[dict[str, Any]] = []
        tools_processed: list[str] = []

        if primary_records:
            normalized_primary = [
                self.normalize_record(rec, "asagus-primary")
                for rec in primary_records
            ]
            all_records.extend(normalized_primary)
            tools_processed.append("asagus-primary")
        
        for tool_id, csv_path in tool_csvs.items():
            records = self.read_csv_records(csv_path)
            if records:
                normalized = [self.normalize_record(rec, tool_id) for rec in records]
                all_records.extend(normalized)
                tools_processed.append(tool_id)
        
        if not all_records:
            return {
                "status": "no_records_found",
                "tools_checked": list(tool_csvs.keys()),
                "records_merged": 0,
            }
        
        # Deduplicate
        unique_records = self.deduplicate_records(all_records)
        
        # Define comprehensive field list
        fieldnames = [
            # Core fields
            "id", "name", "category", "source_tool",
            # Contact
            "phone", "whatsapp", "email", "address",
            # Location
            "city", "country_code", "lat", "lng",
            # Online presence
            "website_url", "facebook_url", "instagram_url", "twitter_url", "linkedin_url",
            # Ratings
            "rating", "review_count",
            # Additional fields that might be present
            "description", "source_url", "method", "confidence", "record_completeness",
            "hours", "price_level", "place_id", "cid",
        ]
        
        # Add any extra fields found in records
        extra_fields: set[str] = set()
        for record in unique_records:
            for key in record.keys():
                if key not in fieldnames and key not in extra_fields:
                    extra_fields.add(key)
        
        fieldnames.extend(sorted(extra_fields))
        
        # Write merged CSV
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            for record in unique_records:
                writer.writerow({k: record.get(k, "") for k in fieldnames})
        
        # Create metadata file
        metadata_path = output_path.with_suffix(".meta.json")
        metadata = {
            "job_id": self.job_id,
            "tools_merged": tools_processed,
            "total_records": len(all_records),
            "unique_records": len(unique_records),
            "duplicates_removed": len(all_records) - len(unique_records),
            "output_path": str(output_path),
            "fieldnames": fieldnames,
        }
        metadata_path.write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")
        
        return {
            "status": "success",
            "job_id": self.job_id,
            "tools_merged": tools_processed,
            "primary_records_included": len(primary_records),
            "records_merged": len(unique_records),
            "duplicates_removed": len(all_records) - len(unique_records),
            "output_csv": str(output_path),
            "output_metadata": str(metadata_path),
        }

    def _extract_domain(self, url: str) -> str:
        """Extract domain from URL."""
        try:
            from urllib.parse import urlparse
            if not url.startswith(("http://", "https://")):
                url = f"https://{url}"
            parsed = urlparse(url)
            return parsed.netloc.lower().removeprefix("www.")
        except Exception:
            return ""

    def get_merge_summary(self) -> dict[str, Any]:
        """Get summary of available tools and their outputs."""
        tool_csvs = self.find_tool_csvs()
        tool_jsons = self.find_tool_jsons()
        
        summary: dict[str, Any] = {
            "job_id": self.job_id,
            "job_dir": str(self.job_dir),
            "job_dir_exists": self.job_dir.exists(),
            "tools_with_csv": [],
            "tools_with_json": [],
            "total_records_available": 0,
        }
        
        for tool_id, csv_path in tool_csvs.items():
            records = self.read_csv_records(csv_path)
            summary["tools_with_csv"].append({
                "tool_id": tool_id,
                "csv_path": str(csv_path),
                "record_count": len(records),
            })
            summary["total_records_available"] += len(records)
        
        for tool_id, json_path in tool_jsons.items():
            try:
                data = json.loads(json_path.read_text(encoding="utf-8"))
                summary["tools_with_json"].append({
                    "tool_id": tool_id,
                    "status": data.get("status"),
                    "json_path": str(json_path),
                })
            except Exception:
                pass
        
        return summary


def merge_download_tools_csv(job_id: str) -> dict[str, Any]:
    """✅ FIX #5: Main entry point for CSV merging."""
    merger = DownloadToolsCSVMerger(job_id)
    return merger.merge_all_csvs()


def merge_asagus_and_download_csv(job_id: str, primary_records: list[dict[str, Any]]) -> dict[str, Any]:
    """Merge the primary ASAGUS DB rows with Download tool CSV artifacts."""
    merger = DownloadToolsCSVMerger(job_id)
    output_path = merger.job_dir / f"combined_primary_and_tools_{merger.job_id}.csv"
    return merger.merge_all_csvs(output_path=output_path, primary_records=primary_records)


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        result = merge_download_tools_csv(sys.argv[1])
        print(json.dumps(result, indent=2))
    else:
        print("Usage: python csv_merger.py <job_id>")
